In [60]:
import pandas as pd

In [61]:
melb_data = pd.read_csv('data/melb_data_ps.csv', sep=',')
melb_data.head()

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Сoordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1,202.0,126.0,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0,156.0,79.0,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0,134.0,150.0,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019,"-37.8093, 144.9944"
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1,94.0,126.0,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,"-37.7969, 144.9969"
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2,120.0,142.0,2014,Yarra,-37.8072,144.9941,Northern Metropolitan,4019,"-37.8072, 144.9941"

In [62]:
melb_df = melb_data.copy()
melb_df.head()

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Сoordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1,202.0,126.0,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0,156.0,79.0,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0,134.0,150.0,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019,"-37.8093, 144.9944"
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1,94.0,126.0,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,"-37.7969, 144.9969"
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2,120.0,142.0,2014,Yarra,-37.8072,144.9941,Northern Metropolitan,4019,"-37.8072, 144.9941"

In [63]:
melb_df = melb_df.drop(['index', 'Сoordinates'], axis=1)
melb_df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067,...,1,1,202.0,126.0,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067,...,1,0,156.0,79.0,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067,...,2,0,134.0,150.0,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067,...,2,1,94.0,126.0,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067,...,1,2,120.0,142.0,2014,Yarra,-37.8072,144.9941,Northern Metropolitan,4019

In [64]:
total_rooms = melb_df['Rooms'] + melb_df['Bedroom'] + melb_df['Bathroom']
total_rooms.head()

0    5
1    5
2    8
3    8
4    8
dtype: int64

In [65]:
melb_df['MeanRoomsSquare'] = melb_df['BuildingArea'] / total_rooms
melb_df['MeanRoomsSquare']

0        25.200000
1        15.800000
2        18.750000
3        15.750000
4        17.750000
           ...
13575    12.600000
13576    16.625000
13577    15.750000
13578    17.444444
13579    12.444444
Name: MeanRoomsSquare, Length: 13580, dtype: float64

In [66]:
diff_area = melb_df['BuildingArea'] - melb_df['Landsize']
sum_area = melb_df['BuildingArea'] + melb_df['Landsize']
melb_df['AreaRatio'] = diff_area / sum_area
melb_df['AreaRatio']

0       -0.231707
1       -0.327660
2        0.056338
3        0.145455
4        0.083969
           ...
13575   -0.676093
13576   -0.429185
13577   -0.551601
13578   -0.693060
13579   -0.527426
Name: AreaRatio, Length: 13580, dtype: float64

In [67]:
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'square': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]
})

countries_df['population density'] = (countries_df['population'] * 1000000) / countries_df['square']
round(countries_df['population density'].mean(), 2)

84.93

In [68]:
melb_df['Date'] = pd.to_datetime(melb_df['Date'])
melb_df['WeekdaySale'] = melb_df['Date'].dt.dayofweek
weekend_count = melb_df[(melb_df['WeekdaySale'] == 5) | (melb_df['WeekdaySale'] == 6)].shape[0]
weekend_count

9226

In [69]:
ufo_data = pd.read_csv('https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv', sep=',')
ufo_df = ufo_data.copy()
ufo_df.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [70]:
ufo_df['Time'] = pd.to_datetime(ufo_df['Time'])
ufo_df.head()

,City,Colors Reported,Shape Reported,State,Time
0,Ithaca,NaN,TRIANGLE,NY,1930-06-01 22:00:00
1,Willingboro,NaN,OTHER,NJ,1930-06-30 20:00:00
2,Holyoke,NaN,OVAL,CO,1931-02-15 14:00:00
3,Abilene,NaN,DISK,KS,1931-06-01 13:00:00
4,New York Worlds Fair,NaN,LIGHT,NY,1933-04-18 19:00:00

In [71]:
ufo_df['Year'] = ufo_df['Time'].dt.year
ufo_df['Year'].mode()[0]

1999

In [72]:
#ufo_df['Delta'] = ufo_df['Time'].dt.date.diff().dt.days
ufo_df[ufo_df['State'] == 'NV']['Time'].dt.date.diff().dt.days.mean()

68.92932862190813

In [73]:
# На вход данной функции поступает строка с адресом.
def get_street_type(address):
# Создаём список географических пометок exclude_list.
    exclude_list = ['N', 'S', 'W', 'E']
# Метод split() разбивает строку на слова по пробелу.
# В результате получаем список слов в строке и заносим его в переменную address_list.
    address_list = address.split(' ')
# Обрезаем список, оставляя в нём только последний элемент,
# потенциальный подтип улицы, и заносим в переменную street_type.
    street_type = address_list[-1]
# Делаем проверку на то, что полученный подтип является географической пометкой.
# Для этого проверяем его на наличие в списке exclude_list.
    if street_type in exclude_list:
# Если переменная street_type является географической пометкой,
# переопределяем её на второй элемент с конца списка address_list.
        street_type = address_list[-2]
# Возвращаем переменную street_type, в которой хранится подтип улицы.
    return street_type

In [74]:
street_types = melb_df['Address'].apply(get_street_type)
street_types

0        St
1        St
2        St
3        La
4        St
         ..
13575    Cr
13576    Dr
13577    St
13578    St
13579    St
Name: Address, Length: 13580, dtype: object

In [75]:
popular_stypes = street_types.value_counts().nlargest(10).index
popular_stypes

Index(['St', 'Rd', 'Ct', 'Dr', 'Av', 'Gr', 'Pde', 'Pl', 'Cr', 'Cl'], dtype='object')

In [76]:
melb_df['StreetType'] = street_types.apply(lambda x: x if x in popular_stypes else 'other')
melb_df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,WeekdaySale,StreetType
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,2016-03-12,2.5,3067,...,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,25.20,-0.231707,5,St
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,2016-04-02,2.5,3067,...,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,15.80,-0.327660,5,St
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,2017-04-03,2.5,3067,...,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019,18.75,0.056338,0,St
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,2017-04-03,2.5,3067,...,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,15.75,0.145455,0,other
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,2016-04-06,2.5,3067,...,2014,Yarra,-37.8072,144.9941,Northern Metropolitan,4019,17.75,0.083969,2,St

In [77]:
melb_df = melb_df.drop('Address', axis=1)
melb_df.head()

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,WeekdaySale,StreetType
0,Abbotsford,2,h,1480000.0,S,Biggin,2016-03-12,2.5,3067,2,...,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,25.20,-0.231707,5,St
1,Abbotsford,2,h,1035000.0,S,Biggin,2016-04-02,2.5,3067,2,...,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,15.80,-0.327660,5,St
2,Abbotsford,3,h,1465000.0,SP,Biggin,2017-04-03,2.5,3067,3,...,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019,18.75,0.056338,0,St
3,Abbotsford,3,h,850000.0,PI,Biggin,2017-04-03,2.5,3067,3,...,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,15.75,0.145455,0,other
4,Abbotsford,4,h,1600000.0,VB,Nelson,2016-04-06,2.5,3067,3,...,2014,Yarra,-37.8072,144.9941,Northern Metropolitan,4019,17.75,0.083969,2,St

In [78]:
#на вход в данную функцию поступает номер дня недели (от 0 до 6) 
def get_weekend(weekday):
    #создаем список выходных дней
    weekend_list = [5, 6]
    #если выходной день возвращаем 1, в противном случае 0
    if weekday in weekend_list:
        return 1
    else:
        return 0

In [79]:
melb_df['Weekend'] = melb_df['WeekdaySale'].apply(get_weekend)
melb_df.head()

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,WeekdaySale,StreetType,Weekend
0,Abbotsford,2,h,1480000.0,S,Biggin,2016-03-12,2.5,3067,2,...,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,25.20,-0.231707,5,St,1
1,Abbotsford,2,h,1035000.0,S,Biggin,2016-04-02,2.5,3067,2,...,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,15.80,-0.327660,5,St,1
2,Abbotsford,3,h,1465000.0,SP,Biggin,2017-04-03,2.5,3067,3,...,Yarra,-37.8093,144.9944,Northern Metropolitan,4019,18.75,0.056338,0,St,0
3,Abbotsford,3,h,850000.0,PI,Biggin,2017-04-03,2.5,3067,3,...,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,15.75,0.145455,0,other,0
4,Abbotsford,4,h,1600000.0,VB,Nelson,2016-04-06,2.5,3067,3,...,Yarra,-37.8072,144.9941,Northern Metropolitan,4019,17.75,0.083969,2,St,0

In [80]:
mask = melb_df['Weekend'] == 1
round(melb_df[mask]['Price'].mean(), 2)

1083291.7

In [81]:
sellerg_popular = melb_df['SellerG'].value_counts().nlargest(49).index
sellerg_popular

Index(['Nelson', 'Jellis', 'hockingstuart', 'Barry', 'Ray', 'Marshall',
       'Buxton', 'Biggin', 'Brad', 'Fletchers', 'Woodards', 'Jas', 'Greg',
       'McGrath', 'Sweeney', 'Noel', 'Miles', 'RT', 'Gary', 'Harcourts',
       'Hodges', 'YPA', 'Stockdale', 'Village', 'Kay', 'Raine', 'Williams',
       'Love', 'Douglas', 'Chisholm', 'RW', 'Rendina', 'HAR', 'O'Brien', 'C21',
       'Collins', 'Cayzer', 'Eview', 'Purplebricks', 'Philip', 'Buckingham',
       'Bells', 'Thomson', 'Nick', 'Alexkarbon', 'McDonald', 'Burnham',
       'Moonee', 'LITTLE'],
      dtype='object')

In [82]:
melb_df['SellerG'] = melb_df['SellerG'].apply(lambda x: x if x in sellerg_popular else 'other')
melb_df.head()

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,WeekdaySale,StreetType,Weekend
0,Abbotsford,2,h,1480000.0,S,Biggin,2016-03-12,2.5,3067,2,...,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,25.20,-0.231707,5,St,1
1,Abbotsford,2,h,1035000.0,S,Biggin,2016-04-02,2.5,3067,2,...,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,15.80,-0.327660,5,St,1
2,Abbotsford,3,h,1465000.0,SP,Biggin,2017-04-03,2.5,3067,3,...,Yarra,-37.8093,144.9944,Northern Metropolitan,4019,18.75,0.056338,0,St,0
3,Abbotsford,3,h,850000.0,PI,Biggin,2017-04-03,2.5,3067,3,...,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,15.75,0.145455,0,other,0
4,Abbotsford,4,h,1600000.0,VB,Nelson,2016-04-06,2.5,3067,3,...,Yarra,-37.8072,144.9941,Northern Metropolitan,4019,17.75,0.083969,2,St,0

In [83]:
mask_nelson = melb_df['SellerG'] == 'Nelson'
mask_other = melb_df['SellerG'] == 'other'
round(melb_df[mask_nelson]['Price'].min() / melb_df[mask_other]['Price'].min(), 1)

1.3

In [84]:
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  object
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  object
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  object
 5   SellerG          13580 non-null  object
 6   Date             13580 non-null  datetime64[ns]
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  YearBuilt        13580 non-null  int64
 15  CouncilArea      12211 non-null  object
 16  Lattitude        13580 non-null  float64
 17  Longtitude       13580 non-null  float64
 18  Regionname       13580 non-null  object
 19  Propertycount    13580 non-null  int64
 20  MeanRoomsSquare  13580 non-null  float64
 21  AreaRatio        13580 non-null  float64
 22  WeekdaySale      13580 non-null  int64
 23  StreetType       13580 non-null  object
 24  Weekend          13580 non-null  int64
dtypes: datetime64[ns](1), float64(8), int64(9), object(7)
memory usage: 2.6+ MB

In [85]:
cols_to_exclude = ['Date', 'Rooms', 'Bedroom', 'Bathroom', 'Car'] # список столбцов, которые мы не берём во внимание
max_unique_count = 150 # задаём максимальное число уникальных категорий
for col in melb_df.columns: # цикл по именам столбцов
    if melb_df[col].nunique() < max_unique_count and col not in cols_to_exclude: # проверяем условие
        melb_df[col] = melb_df[col].astype('category') # преобразуем тип столбца
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  object
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  category
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  category
 5   SellerG          13580 non-null  category
 6   Date             13580 non-null  datetime64[ns]
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  YearBuilt        13580 non-null  category
 15  CouncilArea      12211 non-null  category
 16  Lattitude        13580 non-null  float64
 17  Longtitude       13580 non-null  float64
 18  Regionname       13580 non-null  category
 19  Propertycount    13580 non-null  int64
 20  MeanRoomsSquare  13580 non-null  float64
 21  AreaRatio        13580 non-null  float64
 22  WeekdaySale      13580 non-null  category
 23  StreetType       13580 non-null  category
 24  Weekend          13580 non-null  category
dtypes: category(9), datetime64[ns](1), float64(8), int64(6), object(1)
memory usage: 1.8+ MB

In [86]:
melb_df.head()

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,WeekdaySale,StreetType,Weekend
0,Abbotsford,2,h,1480000.0,S,Biggin,2016-03-12,2.5,3067,2,...,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,25.20,-0.231707,5,St,1
1,Abbotsford,2,h,1035000.0,S,Biggin,2016-04-02,2.5,3067,2,...,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,15.80,-0.327660,5,St,1
2,Abbotsford,3,h,1465000.0,SP,Biggin,2017-04-03,2.5,3067,3,...,Yarra,-37.8093,144.9944,Northern Metropolitan,4019,18.75,0.056338,0,St,0
3,Abbotsford,3,h,850000.0,PI,Biggin,2017-04-03,2.5,3067,3,...,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,15.75,0.145455,0,other,0
4,Abbotsford,4,h,1600000.0,VB,Nelson,2016-04-06,2.5,3067,3,...,Yarra,-37.8072,144.9941,Northern Metropolitan,4019,17.75,0.083969,2,St,0

In [87]:
melb_df['Regionname'].cat.categories

Index(['Eastern Metropolitan', 'Eastern Victoria', 'Northern Metropolitan',
       'Northern Victoria', 'South-Eastern Metropolitan',
       'Southern Metropolitan', 'Western Metropolitan', 'Western Victoria'],
      dtype='object')

In [88]:
melb_df['Regionname'].cat.codes

0        2
1        2
2        2
3        2
4        2
        ..
13575    4
13576    6
13577    6
13578    6
13579    6
Length: 13580, dtype: int8

In [89]:
melb_df['Type'] = melb_df['Type'].cat.rename_categories({
    'u': 'unit',
    't': 'townhouse',
    'h': 'house'
})
melb_df['Type']

0        house
1        house
2        house
3        house
4        house
         ...
13575    house
13576    house
13577    house
13578    house
13579    house
Name: Type, Length: 13580, dtype: category
Categories (3, object): ['house', 'townhouse', 'unit']

In [90]:
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  object
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  category
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  category
 5   SellerG          13580 non-null  category
 6   Date             13580 non-null  datetime64[ns]
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  YearBuilt        13580 non-null  category
 15  CouncilArea      12211 non-null  category
 16  Lattitude        13580 non-null  float64
 17  Longtitude       13580 non-null  float64
 18  Regionname       13580 non-null  category
 19  Propertycount    13580 non-null  int64
 20  MeanRoomsSquare  13580 non-null  float64
 21  AreaRatio        13580 non-null  float64
 22  WeekdaySale      13580 non-null  category
 23  StreetType       13580 non-null  category
 24  Weekend          13580 non-null  category
dtypes: category(9), datetime64[ns](1), float64(8), int64(6), object(1)
memory usage: 1.8+ MB

In [91]:
melb_df['Suburb'].nunique()

314

In [92]:
suburb_popular = melb_df['Suburb'].value_counts().nlargest(119).index
melb_df['Suburb'] = melb_df['Suburb'].apply(lambda x: x if x in suburb_popular else 'other')
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  object
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  category
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  category
 5   SellerG          13580 non-null  category
 6   Date             13580 non-null  datetime64[ns]
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  YearBuilt        13580 non-null  category
 15  CouncilArea      12211 non-null  category
 16  Lattitude        13580 non-null  float64
 17  Longtitude       13580 non-null  float64
 18  Regionname       13580 non-null  category
 19  Propertycount    13580 non-null  int64
 20  MeanRoomsSquare  13580 non-null  float64
 21  AreaRatio        13580 non-null  float64
 22  WeekdaySale      13580 non-null  category
 23  StreetType       13580 non-null  category
 24  Weekend          13580 non-null  category
dtypes: category(9), datetime64[ns](1), float64(8), int64(6), object(1)
memory usage: 1.8+ MB