In [7]:
import pandas as pd
import numpy as np

In [45]:
citibike_tripdata = pd.read_csv('data/citibike-tripdata.csv', sep=',')
citibike_df = citibike_tripdata.copy()
citibike_df.head()

,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,2018-09-01 00:00:05.2690,2018-09-01 00:27:20.6340,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,25577,Subscriber,1980,1
1,2018-09-01 00:00:11.2810,2018-09-01 00:02:23.4810,314.0,Cadman Plaza West & Montague St,40.693830,-73.990539,3242.0,Schermerhorn St & Court St,40.691029,-73.991834,34377,Subscriber,1969,0
2,2018-09-01 00:00:20.6490,2018-09-01 00:55:58.5470,3142.0,1 Ave & E 62 St,40.761227,-73.960940,3384.0,Smith St & 3 St,40.678724,-73.995991,30496,Subscriber,1975,1
3,2018-09-01 00:00:21.7460,2018-09-01 00:07:38.5830,308.0,St James Pl & Oliver St,40.713079,-73.998512,3690.0,Park Pl & Church St,40.713342,-74.009355,28866,Subscriber,1984,2
4,2018-09-01 00:00:27.3150,2018-09-01 02:21:25.3080,345.0,W 13 St & 6 Ave,40.736494,-73.997044,380.0,W 4 St & 7 Ave S,40.734011,-74.002939,20943,Customer,1994,1

In [4]:
citibike_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   starttime                300000 non-null  object
 1   stoptime                 300000 non-null  object
 2   start station id         299831 non-null  float64
 3   start station name       299831 non-null  object
 4   start station latitude   300000 non-null  float64
 5   start station longitude  300000 non-null  float64
 6   end station id           299831 non-null  float64
 7   end station name         299831 non-null  object
 8   end station latitude     300000 non-null  float64
 9   end station longitude    300000 non-null  float64
 10  bikeid                   300000 non-null  int64
 11  usertype                 300000 non-null  object
 12  birth year               300000 non-null  int64
 13  gender                   300000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 32.0+ MB

In [17]:
mask = pd.isnull(citibike_df['start station id'])
citibike_df[mask].shape[0]

169

In [18]:
citibike_df['start station id'].mode()

0    281.0
dtype: float64

In [19]:
citibike_df['bikeid'].mode()

0    33887
dtype: int64

In [24]:
round(citibike_df['usertype'].value_counts(normalize=True)[0], 2)

0.77

In [25]:
citibike_df['gender'].value_counts()

1    183582
2     74506
0     41912
Name: gender, dtype: int64

In [27]:
citibike_df['start station id'].nunique()

759

In [28]:
citibike_df['end station id'].nunique()

765

In [46]:
citibike_df['starttime'] = pd.to_datetime(citibike_df['starttime'])
citibike_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   starttime                300000 non-null  datetime64[ns]
 1   stoptime                 300000 non-null  object
 2   start station id         299831 non-null  float64
 3   start station name       299831 non-null  object
 4   start station latitude   300000 non-null  float64
 5   start station longitude  300000 non-null  float64
 6   end station id           299831 non-null  float64
 7   end station name         299831 non-null  object
 8   end station latitude     300000 non-null  float64
 9   end station longitude    300000 non-null  float64
 10  bikeid                   300000 non-null  int64
 11  usertype                 300000 non-null  object
 12  birth year               300000 non-null  int64
 13  gender                   300000 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(3), object(4)
memory usage: 32.0+ MB

In [35]:
citibike_df['age'] = citibike_df['starttime'].dt.year - citibike_df['birth year']
citibike_df.head()

,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,age
0,2018-09-01 00:00:05.269,2018-09-01 00:27:20.6340,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,25577,Subscriber,1980,1,38
1,2018-09-01 00:00:11.281,2018-09-01 00:02:23.4810,314.0,Cadman Plaza West & Montague St,40.693830,-73.990539,3242.0,Schermerhorn St & Court St,40.691029,-73.991834,34377,Subscriber,1969,0,49
2,2018-09-01 00:00:20.649,2018-09-01 00:55:58.5470,3142.0,1 Ave & E 62 St,40.761227,-73.960940,3384.0,Smith St & 3 St,40.678724,-73.995991,30496,Subscriber,1975,1,43
3,2018-09-01 00:00:21.746,2018-09-01 00:07:38.5830,308.0,St James Pl & Oliver St,40.713079,-73.998512,3690.0,Park Pl & Church St,40.713342,-74.009355,28866,Subscriber,1984,2,34
4,2018-09-01 00:00:27.315,2018-09-01 02:21:25.3080,345.0,W 13 St & 6 Ave,40.736494,-73.997044,380.0,W 4 St & 7 Ave S,40.734011,-74.002939,20943,Customer,1994,1,24

In [41]:
mask = (citibike_df['starttime'].dt.year == 2018) & (citibike_df['starttime'].dt.month == 9)
citibike_df[mask]['age'].min()

16

In [43]:
citibike_df['start station name'].value_counts()

Grand Army Plaza & Central Park S    1928
Central Park S & 6 Ave               1909
Pershing Square North                1873
12 Ave & W 40 St                     1845
West St & Chambers St                1835
                                     ...
NYCBS Depot - GOW                      15
Franklin Ave & Empire Blvd             11
Railroad Ave & Kay Ave                  9
47 Ave & Skillman Ave                   7
Eastern Pkwy & Washington Ave           6
Name: start station name, Length: 759, dtype: int64

In [44]:
citibike_df['end station name'].value_counts()

West St & Chambers St          1963
12 Ave & W 40 St               1909
Pershing Square North          1850
Central Park S & 6 Ave         1828
E 17 St & Broadway             1804
                               ...
Exchange Place                    3
Liberty Light Rail                1
Montrose Ave & Bushwick Ave       1
Union St                          1
Warren St                         1
Name: end station name, Length: 765, dtype: int64

In [47]:
citibike_df = citibike_df.drop(['start station id', 'end station id'], axis=1)
citibike_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 12 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   starttime                300000 non-null  datetime64[ns]
 1   stoptime                 300000 non-null  object
 2   start station name       299831 non-null  object
 3   start station latitude   300000 non-null  float64
 4   start station longitude  300000 non-null  float64
 5   end station name         299831 non-null  object
 6   end station latitude     300000 non-null  float64
 7   end station longitude    300000 non-null  float64
 8   bikeid                   300000 non-null  int64
 9   usertype                 300000 non-null  object
 10  birth year               300000 non-null  int64
 11  gender                   300000 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(3), object(4)
memory usage: 27.5+ MB

In [49]:
citibike_df['age'] = 2018 - citibike_df['birth year']
citibike_df[citibike_df['age'] > 60].shape[0]

11837

In [54]:
citibike_df['stoptime'] = pd.to_datetime(citibike_df['stoptime'])
citibike_df['trip duration'] = (citibike_df['stoptime'] - citibike_df['starttime']).dt.seconds
round(citibike_df['trip duration'].mean(), 0)

1000.0

In [57]:
citibike_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   starttime                300000 non-null  datetime64[ns]
 1   stoptime                 300000 non-null  datetime64[ns]
 2   start station name       299831 non-null  object
 3   start station latitude   300000 non-null  float64
 4   start station longitude  300000 non-null  float64
 5   end station name         299831 non-null  object
 6   end station latitude     300000 non-null  float64
 7   end station longitude    300000 non-null  float64
 8   bikeid                   300000 non-null  int64
 9   usertype                 300000 non-null  object
 10  birth year               300000 non-null  int64
 11  gender                   300000 non-null  int64
 12  age                      300000 non-null  int64
 13  trip duration            300000 non-null  int64
dtypes: datetime64[ns](2), float64(4), int64(5), object(3)
memory usage: 32.0+ MB

In [60]:
weekend_list = [5, 6]
citibike_df['weekend'] = citibike_df['starttime'].dt.dayofweek.apply(lambda x: 1 if x in weekend_list else 0)
citibike_df[citibike_df['weekend'] == 1].shape[0]

115135

In [62]:
def time_of_day(hour):
    night_list = list(range(0, 7))
    morning_list = list(range(7, 13))
    day_list = list(range(13, 19))
    evening_list = list(range(19, 24))
    if hour in night_list:
        return 'night'
    if hour in morning_list:
        return 'morning'
    if hour in day_list:
        return 'day'
    if hour in evening_list:
        return 'evening'

In [64]:
citibike_df['time_of_day'] = citibike_df['starttime'].dt.hour.apply(time_of_day)
trip_day = citibike_df[citibike_df['time_of_day'] == 'day'].shape[0]
trip_night = citibike_df[citibike_df['time_of_day'] == 'night'].shape[0]
round(trip_day / trip_night, 0)

9.0