In [1]:
import pandas as pd

In [2]:
movies_data = pd.read_csv('data/movies.csv', sep=',')
dates_data = pd.read_csv('data/dates.csv', sep=',')
ratings1_data = pd.read_csv('data/ratings1.csv', sep=',')
ratings2_data = pd.read_csv('data/ratings2.csv', sep=',')

In [3]:
movies_df = movies_data.copy()
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
dates_df = dates_data.copy() 
dates_df.head()

                  date
0  2000-07-30 18:45:03
1  2000-07-30 18:20:47
2  2000-07-30 18:37:04
3  2000-07-30 19:03:35
4  2000-07-30 18:48:51

In [5]:
ratings1_df = ratings1_data.copy()
ratings1_df.head()

   userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [6]:
ratings2_df = ratings2_data.copy()
ratings2_df.head()

   userId  movieId  rating
0     274     5621     2.0
1     274     5630     3.0
2     274     5667     3.5
3     274     5679     3.5
4     274     5690     3.0

In [12]:
movies_df['movieId'].nunique()

9742

In [14]:
ratings1_df['userId'].nunique()

274

In [19]:
pd.to_datetime(dates_df['date']).dt.year.value_counts().sort_values()

1998      507
2014     1439
2013     1664
2011     1690
1997     1916
2010     2301
1999     2439
2004     3279
2002     3478
2001     3922
2003     4014
2006     4059
2009     4158
2008     4351
2012     4656
2005     5813
1996     6040
2018     6418
2015     6616
2016     6703
2007     7114
2017     8198
2000    10061
Name: date, dtype: int64

In [7]:
ratings = pd.concat(
    [ratings1_df, ratings2_df],
    ignore_index=True
)
ratings

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100832     610   166534     4.0
100833     610   168248     5.0
100834     610   168250     5.0
100835     610   168252     5.0
100836     610   170875     3.0

[100837 rows x 3 columns]

In [8]:
ratings = ratings.drop_duplicates(ignore_index=True)
ratings

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [9]:
ratings_dates = pd.concat([ratings, dates_df], axis=1)
ratings_dates.tail(7)

        userId  movieId  rating                 date
100829     610   164179     5.0  2017-05-03 21:07:11
100830     610   166528     4.0  2017-05-04 06:29:25
100831     610   166534     4.0  2017-05-03 21:53:22
100832     610   168248     5.0  2017-05-03 22:21:31
100833     610   168250     5.0  2017-05-08 19:50:47
100834     610   168252     5.0  2017-05-03 21:19:12
100835     610   170875     3.0  2017-05-03 21:20:15

In [11]:
joined_false = ratings_dates.join(
    movies_df,
    rsuffix='_right',
    how='left'
)
joined_false

,userId,movieId,rating,date,movieId_right,title,genres
0,1,1,4.0,2000-07-30 18:45:03,1.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,2.0,Jumanji (1995),Adventure|Children|Fantasy
2,1,6,4.0,2000-07-30 18:37:04,3.0,Grumpier Old Men (1995),Comedy|Romance
3,1,47,5.0,2000-07-30 19:03:35,4.0,Waiting to Exhale (1995),Comedy|Drama|Romance
4,1,50,5.0,2000-07-30 18:48:51,5.0,Father of the Bride Part II (1995),Comedy
...,...,...,...,...,...,...,...
100831,610,166534,4.0,2017-05-03 21:53:22,NaN,NaN,NaN
100832,610,168248,5.0,2017-05-03 22:21:31,NaN,NaN,NaN
100833,610,168250,5.0,2017-05-08 19:50:47,NaN,NaN,NaN
100834,610,168252,5.0,2017-05-03 21:19:12,NaN,NaN,NaN
100835,610,170875,3.0,2017-05-03 21:20:15,NaN,NaN,NaN

In [12]:
joined = ratings_dates.join(
    movies_df.set_index('movieId'),
    on='movieId',
    how='left'
)
joined

,userId,movieId,rating,date,title,genres
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
...,...,...,...,...,...,...
100831,610,166534,4.0,2017-05-03 21:53:22,Split (2017),Drama|Horror|Thriller
100832,610,168248,5.0,2017-05-03 22:21:31,John Wick: Chapter Two (2017),Action|Crime|Thriller
100833,610,168250,5.0,2017-05-08 19:50:47,Get Out (2017),Horror
100834,610,168252,5.0,2017-05-03 21:19:12,Logan (2017),Action|Sci-Fi
100835,610,170875,3.0,2017-05-03 21:20:15,The Fate of the Furious (2017),Action|Crime|Drama|Thriller

In [14]:
merged = ratings_dates.merge(
    movies_df,
    on='movieId',
    how='left'
)
merged

,userId,movieId,rating,date,title,genres
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
...,...,...,...,...,...,...
100831,610,166534,4.0,2017-05-03 21:53:22,Split (2017),Drama|Horror|Thriller
100832,610,168248,5.0,2017-05-03 22:21:31,John Wick: Chapter Two (2017),Action|Crime|Thriller
100833,610,168250,5.0,2017-05-08 19:50:47,Get Out (2017),Horror
100834,610,168252,5.0,2017-05-03 21:19:12,Logan (2017),Action|Sci-Fi
100835,610,170875,3.0,2017-05-03 21:20:15,The Fate of the Furious (2017),Action|Crime|Drama|Thriller